import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  apotheosisSidebar: [{type: 'autogenerated', dirName: 'apotheosis'}],
  skillSystemSidebar: [{type: 'autogenerated', dirName: 'skill-system'}],
  spellEngineSidebar: [{type: 'autogenerated', dirName: 'spell-engine'}],
  silentGearSidebar: [{type: 'autogenerated', dirName: 'silent-gear'}],
  createSidebar: [{type: 'autogenerated', dirName: 'create'}],
  mekanismSidebar: [{type: 'autogenerated', dirName: 'mekanism'}],
  ae2Sidebar: [{type: 'autogenerated', dirName: 'ae2'}],
  idasSidebar: [{type: 'autogenerated', dirName: 'idas'}],
  cataclysmSidebar: [{type: 'autogenerated', dirName: 'cataclysm'}],
  classesSidebar: [{type: 'autogenerated', dirName: 'classes'}],
  recommendedSidebar: [{type: 'autogenerated', dirName: 'guide-recommended'}],
  wikiReferenceSidebar: [{type: 'autogenerated', dirName: 'wiki-reference'}],
};

export default sidebars;
