import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  userGuideSidebar: [
    {
      type: 'category',
      label: '유저 가이드',
      link: {type: 'doc', id: 'user-guide/beginners-guide/index'},
      items: [{type: 'autogenerated', dirName: 'user-guide'}],
    },
  ],
  apotheosisSidebar: [
    {
      type: 'category',
      label: 'Apotheosis',
      link: {type: 'doc', id: 'apotheosis/overview'},
      items: [{type: 'autogenerated', dirName: 'apotheosis'}],
    },
  ],
  skillSystemSidebar: [
    {
      type: 'category',
      label: 'RPG Skill Trees',
      link: {type: 'doc', id: 'skill-system/overview'},
      items: [{type: 'autogenerated', dirName: 'skill-system'}],
    },
  ],
  spellEngineSidebar: [
    {
      type: 'category',
      label: 'Spell Engine',
      link: {type: 'doc', id: 'spell-engine/overview'},
      items: [{type: 'autogenerated', dirName: 'spell-engine'}],
    },
  ],
  silentGearSidebar: [
    {
      type: 'category',
      label: 'Silent Gear',
      link: {type: 'doc', id: 'silent-gear/overview'},
      items: [{type: 'autogenerated', dirName: 'silent-gear'}],
    },
  ],
  createSidebar: [
    {
      type: 'category',
      label: 'Create',
      link: {type: 'doc', id: 'create/overview'},
      items: [{type: 'autogenerated', dirName: 'create'}],
    },
  ],
  mekanismSidebar: [
    {
      type: 'category',
      label: 'Mekanism',
      link: {type: 'doc', id: 'mekanism/overview'},
      items: [{type: 'autogenerated', dirName: 'mekanism'}],
    },
  ],
  ae2Sidebar: [
    {
      type: 'category',
      label: 'Applied Energistics 2',
      link: {type: 'doc', id: 'ae2/overview'},
      items: [{type: 'autogenerated', dirName: 'ae2'}],
    },
  ],
  idasSidebar: [
    {
      type: 'category',
      label: 'Integrated Dungeons And Structures',
      link: {type: 'doc', id: 'idas/overview'},
      items: [{type: 'autogenerated', dirName: 'idas'}],
    },
  ],
  cataclysmSidebar: [
    {
      type: 'category',
      label: 'Cataclysm',
      link: {type: 'doc', id: 'cataclysm/overview'},
      items: [{type: 'autogenerated', dirName: 'cataclysm'}],
    },
  ],
  classesSidebar: [
    {
      type: 'category',
      label: 'RPG Classes',
      link: {type: 'doc', id: 'classes/class-overview'},
      items: [{type: 'autogenerated', dirName: 'classes'}],
    },
  ],
  recommendedSidebar: [
    {
      type: 'category',
      label: 'Weapon and Others',
      link: {type: 'doc', id: 'guide-recommended/archers-armory-arsenal'},
      items: [{type: 'autogenerated', dirName: 'guide-recommended'}],
    },
  ],
  wikiReferenceSidebar: [
    {
      type: 'category',
      label: 'Dungeons mods',
      link: {type: 'doc', id: 'wiki-reference/dungeons-arise'},
      items: [{type: 'autogenerated', dirName: 'wiki-reference'}],
    },
  ],
};

export default sidebars;
