import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Apotheosis',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'apotheosis'}],
    },
    {
      type: 'category',
      label: '스킬 시스템',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'skill-system'}],
    },
    {
      type: 'category',
      label: '마법 시스템 (Spell Engine)',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'spell-engine'}],
    },
    {
      type: 'category',
      label: '장비 제작 (Silent Gear)',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'silent-gear'}],
    },
    {
      type: 'category',
      label: '자동화 (Create)',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'create'}],
    },
    {
      type: 'category',
      label: '산업 자동화 (Mekanism)',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'mekanism'}],
    },
  ],
};

export default sidebars;
